version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    networks:
      - mynetwork

  python-consumer:
    build:
      context: ./consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: webtracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    networks:
      - mynetwork

  python-producer:
    build:
      context: ./producer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - mynetwork

networks:
  mynetwork:
